# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, b'In afwachting'), (2, b'Goedgekeurd'), (3, b'Geannuleerd')], default=1)),
                ('intro_completed', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=b'', max_length=200, verbose_name=b'Voornaam')),
                ('last_name', models.CharField(default=b'', max_length=200, verbose_name=b'Achternaam')),
                ('birth', models.DateField(blank=True, null=True, verbose_name=b'Geboortedatum')),
                ('tel', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Het telefoonnummer moet 10 cijfers bevatten en beginnen met "06".', regex=b'^((06){1}[1-9]{1}[0-9]{7})$')], verbose_name=b'Mobiel Telefoonnummer (0612345678)')),
            ],
        ),
    ]
