# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 18:59
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=b'images/profile/', verbose_name=b'Image'),
        ),
    ]
