# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_sale_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
