# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_auto_20151231_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
