# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaid',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
