# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_auto_20160101_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200, verbose_name=b'Titel')),
                ('slug', models.CharField(default=b'', max_length=200, verbose_name=b'Titel')),
                ('amount', models.FloatField(verbose_name=b'Aantal')),
                ('image', models.ImageField(upload_to=b'', verbose_name=b'Afbeelding')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.Product', verbose_name=b'Betreffend product')),
            ],
        ),
    ]
