# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0010_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='badge',
            name='amount',
        ),
        migrations.AddField(
            model_name='badge',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.CharField(default=b'', max_length=200, verbose_name=b'slug'),
        ),
        migrations.AddField(
            model_name='user_badge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.Badge'),
        ),
        migrations.AddField(
            model_name='user_badge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
