# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_auto_20160123_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='amount',
            field=models.FloatField(verbose_name=b"Aantal euro's"),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Koper'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'Naam'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.5, verbose_name=b'Prijs'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(verbose_name=b'Aantal'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(verbose_name=b'Inkoopprijs per stuk'),
        ),
    ]
