# Generated by Django 3.2.8 on 2021-10-21 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0012_auto_20160123_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.product', verbose_name='Betreffend product'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='amount',
            field=models.FloatField(verbose_name="Aantal euro's"),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Koper'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.5, verbose_name='Prijs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Geboortedatum'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(1, 'In afwachting'), (2, 'Goedgekeurd'), (3, 'Geannuleerd')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Het telefoonnummer moet 10 cijfers bevatten en beginnen met "06".', regex='^((06){1}[1-9]{1}[0-9]{7})$')], verbose_name='Mobiel Telefoonnummer (0612345678)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myproject.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(verbose_name='Aantal'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(verbose_name='Inkoopprijs per stuk'),
        ),
    ]
