# Generated by Django 3.2.8 on 2021-11-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
